bugs & ticket transactions
CASL-AE/xrpl.c pull request #23
Opened 2022-08-04 20:35 UTC by Platonenkov

double parse, hex name, Quality - errors
Error info add
ticket transaction add

2022-08-04 21:28 UTC, dangell7 commented
I'll merge with the above changes, however, in the future once I have refactored the library completely you would need to submit tests for some of these functions.

2022-08-05 05:39 UTC, Platonenkov commented
> I'll merge with the above changes, however, in the future once I have refactored the library completely you would need to submit tests for some of these functions.

ok, just say what exactly

2022-08-05 15:26 UTC, dangell7 requested changes

2022-08-05 15:26 UTC, dangell7 commented on Xrpl.C/Xrpl/Client/Models/Transaction/TicketCreateCreateTransaction.cs
> +﻿using Newtonsoft.Json;
Can you update this function to match this? Those other fields are ledger object fields and should be on the ticket ledger object.

https://github.com/Transia-RnD/xrpl.c/blob/ad3c8a961f545ff12b192964d2749aabfe218935/Xrpl.C/Xrpl/Client/Models/Transaction/TicketCreateTransaction.cs

2022-08-05 15:26 UTC, dangell7 commented on Xrpl.C/Xrpl/Client/Extensions/ExtensionHelpers.cs
> +        public static string FromHexUtf8String(this string input)
Can you change the name to FromHexString and remove the function above? You are right, it should be UTF8.

2022-08-05 15:26 UTC, dangell7 commented on Xrpl.C/Xrpl.C.csproj
> -    <Folder Include="Xrpl\" />
And I'm just curious why these are removed. C# isn't my expert language so I was curious.

2022-08-05 16:14 UTC, Platonenkov commented on Xrpl.C/Xrpl.C.csproj
> -    <Folder Include="Xrpl\" />
this item group not need for new csproj file type type

2022-08-05 16:23 UTC, Platonenkov commented on Xrpl.C/Xrpl/Client/Extensions/ExtensionHelpers.cs
> +        public static string FromHexUtf8String(this string input)
done

2022-08-05 16:32 UTC, Platonenkov commented on Xrpl.C/Xrpl/Client/Models/Transaction/TicketCreateCreateTransaction.cs
> +﻿using Newtonsoft.Json;
done
https://github.com/Platonenkov/xrpl.CSharp/commit/ab4ea3851fceb9db9fad64c30e53a6bb07cbdb6f

2022-08-05 17:31 UTC, Platonenkov commented on Xrpl.C/Xrpl/Client/Extensions/ExtensionHelpers.cs
> +        public static string FromHexUtf8String(this string input)
Can I refactoring to improve code readability?
I'm a .Net developer and it pains me to look at some forms of recording...
https://github.com/Platonenkov/xrpl.CSharp/commit/1d7e1f4cfa740b0e53c40035a6d56080b1b8bf07

2022-08-05 20:55 UTC, dangell7 commented on Xrpl.C/Xrpl/Client/Models/Methods/AccountOffers.cs
> +        public double Quality { get; set; }
string

2022-08-05 20:55 UTC, dangell7 requested changes
see the one change above.

2022-08-05 20:56 UTC, dangell7 commented on Xrpl.C/Xrpl/Client/Extensions/ExtensionHelpers.cs
> +        public static string FromHexUtf8String(this string input)
I will merge this, then you merge those into dev and create another PR and I'll approve it. Just so it's clear and these changes dont get lost in a big PR.

2022-08-06 00:00 UTC, dangell7 approved these changes

2022-08-06 00:00 UTC, merged

2022-08-06 05:25 UTC, Platonenkov commented on Xrpl.C/Xrpl/Client/Models/Methods/AccountOffers.cs
> +        public double Quality { get; set; }
https://github.com/Transia-RnD/xrpl.c/pull/24
done